Update shellcheck.yml

diff --git a/.github/workflows/shellcheck.yml b/.github/workflows/shellcheck.yml
--- a/.github/workflows/shellcheck.yml
+++ b/.github/workflows/shellcheck.yml
@@ -269,25 +269,25 @@ jobs:
               - ZC1330 # Avoid `$INPUTRC` in Zsh — Zsh uses `bindkey` and ZLE, not readline. `INPUTRC` is Bash-specific.
 
       - name: "ZShellCheck (style)"
-        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE zshellcheck --severity style
+        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE bash -eo pipefail -c "${Z_SHELL_CHECK_SH}"
         env:
           SHELL_FILES_JSON: ${{ steps.linguist.outputs.shell-json }}
           Z_SHELL_CHECK_SH: zshellcheck --severity style --format json FILE | jq "${JQ_QUERY}"
 
       - name: "ZShellCheck (info)"
-        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE zshellcheck --severity style
+        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE bash -eo pipefail -c "${Z_SHELL_CHECK_SH}"
         env:
           SHELL_FILES_JSON: ${{ steps.linguist.outputs.shell-json }}
           Z_SHELL_CHECK_SH: zshellcheck --severity info --format json FILE | jq "${JQ_QUERY}"
 
       - name: "ZShellCheck (warning)"
-        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE zshellcheck --severity style
+        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE bash -eo pipefail -c "${Z_SHELL_CHECK_SH}"
         env:
           SHELL_FILES_JSON: ${{ steps.linguist.outputs.shell-json }}
           Z_SHELL_CHECK_SH: zshellcheck --severity warning --format json FILE | jq "${JQ_QUERY}"
 
       - name: "ZShellCheck (error)"
-        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE zshellcheck --severity style
+        run: echo "$SHELL_FILES_JSON" | jq --raw-output '.[]' | xargs -IFILE bash -eo pipefail -c "${Z_SHELL_CHECK_SH}"
         env:
           SHELL_FILES_JSON: ${{ steps.linguist.outputs.shell-json }}
           Z_SHELL_CHECK_SH: zshellcheck --severity error --format json FILE | jq "${JQ_QUERY}"
